### ISSUE TITLE
ValueError: operands could not be broadcast together

### ISSUE THREAD

**Issue by Vishruth-Sham** [yaochenzhu/Deep-Deconf#5]
```
Traceback (most recent call last):
  File "simulate.py", line 270, in <module>
    simulate()
  File "simulate.py", line 201, in simulate
    rat_dist = get_rat_dist(rat_table)
  File "simulate.py", line 62, in get_rat_dist
    return adj_rat_dist(rat_dist_raw)
  File "simulate.py", line 55, in adj_rat_dist
    rat_dist_raw = rat_dist_raw*weights
ValueError: operands could not be broadcast together with shapes (138,) (5,)
```

Gettig this error in simulate.py, could you please suggest a fix?

**Comment by yaochenzhu** [comment]
Basically, adj_rat_dist function adjusts the rating distribution, i.e., percentage of 1,2,3,4,5, of the observed dataset. I don't know why you have shape (138,), maybe you should check this part...
